{"error code":"Forbidden","url":"Ocured an error in path /login","message":"\"Bad login/password combination\"","stack":"ForbittenError: Bad login/password combination\n    at Object.loginUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\login\\login.service.js:16:13)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\login\\login.router.js:9:23\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:16:35"}
{"error code":"Conflict","url":"Ocured an error in path /users","message":"\"User with login rus_g@tut.by already exist\"","stack":"ConflictError: User with login rus_g@tut.by already exist\n    at registerUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\login\\login.service.js:33:11)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:79:27\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:17:03"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:19:34"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:23:33"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:25:29"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:26:00"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:26:30"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:27:50"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:30:05"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:30:21"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:30:46"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:30:50"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:32:16"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:33:52"}
{"error code":"Conflict","url":"Ocured an error in path /users/da2d435f-4d61-4ec6-b445-45d44d5b89d1","message":"\"User with login test@test.by already exist\"","stack":"ConflictError: User with login test@test.by already exist\n    at Object.updateUser (D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.db.repository.js:32:13)\n    at runMicrotasks (<anonymous>)\n    at processTicksAndRejections (internal/process/task_queues.js:93:5)\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\resources\\users\\user.router.js:90:18\n    at async D:\\Rolling_scopes\\rsclone\\server\\src\\errors\\catchError.js:3:12","level":"error","timestamp":"2021-02-02 21:35:05"}
